# docker-compose.yml
version: "3.9"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123